apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: glob

namespace: glob

resources:
  - namespace.yaml
  - https://github.com/baarsgaard/glob/deploy/?ref:v0.1.0

images:
  - name: ghcr.io/baarsgaard/glob
    newTag: v0.1.0

patches:
  # Override ingress
  - path: ingress.yaml
  - patch: |-
      - op: add
        path: /spec/rules/0/host
        value: glob.example.com
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: glob
