---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glob-data
  labels:
    app.kubernetes.io/name: glob
    app.kubernetes.io/component: data
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
