name: release

on:
  push:
    tags:
      - "*"

permissions:
  packages: write

jobs:
  ko_image:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - uses: ko-build/setup-ko@v0.8

      - name: Build and push
        run: |
          export KO_DOCKER_REPO="$(echo 'ghcr.io/${{ github.repository }}' | tr '[:upper:]' '[:lower:]')"
          ko build --bare --platform linux/arm64,linux/arm/v7,linux/amd64,linux/ppc64le -t "${{ github.ref_name }}" \
            --image-label org.opencontainers.image.title=baarsgaard/glob \
            --image-label org.opencontainers.image.description="Minimal blob repository without bells and whistles" \
            --image-label org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }} \
            --image-label org.opencontainers.image.revision=${{ github.sha }} \
            --image-label org.opencontainers.image.version=${{ github.ref_name }} \
            --image-label org.opencontainers.image.created=${{ env.BUILD_DATE }}
